### ISSUE TITLE
Add filters to a drawer

### ISSUE THREAD

**Issue by cegrief** [eecs394-spr15/DormIt#25]

**Comment by mingyueding** [comment]
Chen and I added the drawer. But I directly committed changes to master because I didn't realize I was working in the master... Sorry about that. Luckily, there are only minor change in structure.coffee.

**Comment by mingyueding** [comment]
Also, the search bar previously in search.html was moved to the homepage.

**Comment by cegrief** [comment]
woops, nevermind
