### ISSUE TITLE
Get sliders working for filters

### ISSUE THREAD

**Issue by cegrief** [eecs394-spr15/DormIt#46]

**Comment by cegrief** [comment]
when choosing a javascript library, always try to find one labelled "angular"

**Comment by mingyueding** [comment]
Done! But haven't merge to master, because we don't have attribute "Star" in Parse.

**Comment by cegrief** [comment]
@mingyueding Feel free to add the star attribute in with some mock data for now! If you log into parse its pretty intuitive to just add a column and then put numbers into the table.

**Comment by mingyueding** [comment]
that is what i am going to do
